CREATE SCHEMA IF NOT EXISTS wsc;

SET SCHEMA wsc;

CREATE TABLE IF NOT EXISTS TEMPERATURE (
  ID          INT AUTO_INCREMENT PRIMARY KEY,
  sensor_id   VARCHAR(45) NOT NULL,
  temperature FLOAT NOT NULL,
  datetime    DATETIME NOT NULL,
  location    VARCHAR(500) NOT NULL,
);

CREATE TABLE IF NOT EXISTS USERS (
  ID        INT AUTO_INCREMENT PRIMARY KEY,
  name      VARCHAR(30),
  email     VARCHAR(50),
  password  VARCHAR(80),
  age       INTEGER
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
  ID        INT AUTO_INCREMENT PRIMARY KEY,
  user_id   INTEGER,
  role      VARCHAR(100),
);


SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE USERS;
TRUNCATE TABLE AUTHORITIES;
TRUNCATE TABLE TEMPERATURE;
SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO TEMPERATURE VALUES (1, 'temp1', 32.4, '2015-05-15 08:18:24', '1st Floor, 4th Engineering Building, KoreaTech');
INSERT INTO TEMPERATURE VALUES (2, 'temp2', 34.9, '2015-05-16 08:10:54', '3st Floor, 2th Engineering Building, KoreaTech');